# Generated by Django 5.2.17 on 2026-10-03 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('year_level', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +63 917 555 4821.', regex='^\\+?[0-9][0-9 \\-()]{6,19}$')])),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, verbose_name='Conditions & notes')),
                ('emergency_name', models.CharField(blank=True, max_length=120)),
                ('emergency_relationship', models.CharField(blank=True, max_length=60)),
                ('emergency_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, for example +63 917 555 4821.', regex='^\\+?[0-9][0-9 \\-()]{6,19}$')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_alerts', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('queue_sound', models.BooleanField(default=False)),
                ('auto_triage', models.BooleanField(default=True)),
                ('share_anon_stats', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
